services:
  db:
    image: postgres:16
    container_name: sbom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sbom_browser
    ports:
      - "5432:5432"
    volumes:
      - sbom_pgdata:/var/lib/postgresql/data

volumes:
  sbom_pgdata:
